"""Add is_admin column to users

Revision ID: ad2fbe9e404c
Revises: 65b970631326
Create Date: 2026-02-08 18:14:35.497505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad2fbe9e404c'
down_revision: Union[str, Sequence[str], None] = '65b970631326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_pizza_variant_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'order_items', 'pizza_variants', ['pizza_variant_id'], ['id'], ondelete='CASCADE')
    op.alter_column('pizza_variants', 'size',
               existing_type=postgresql.ENUM('LARGE', 'MEDIUM', 'SMALL', name='pizza_size_enum'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('pizza_variants_pizza_id_fkey'), 'pizza_variants', type_='foreignkey')
    op.create_foreign_key(None, 'pizza_variants', 'pizzas', ['pizza_id'], ['id'], ondelete='CASCADE')
    op.add_column('pizzas', sa.Column('name', sa.String(), nullable=False))
    op.add_column('pizzas', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pizzas', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_pizzas_id'), table_name='pizzas')
    op.drop_column('pizzas', 'compound')
    op.drop_column('pizzas', 'pizza_name')
    op.drop_column('pizzas', 'photo')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_admin')
    op.add_column('pizzas', sa.Column('photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pizzas', sa.Column('pizza_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pizzas', sa.Column('compound', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_pizzas_id'), 'pizzas', ['id'], unique=False)
    op.drop_column('pizzas', 'is_active')
    op.drop_column('pizzas', 'description')
    op.drop_column('pizzas', 'name')
    op.drop_constraint(None, 'pizza_variants', type_='foreignkey')
    op.create_foreign_key(op.f('pizza_variants_pizza_id_fkey'), 'pizza_variants', 'pizzas', ['pizza_id'], ['id'])
    op.alter_column('pizza_variants', 'size',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LARGE', 'MEDIUM', 'SMALL', name='pizza_size_enum'),
               existing_nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_pizza_variant_id_fkey'), 'order_items', 'pizza_variants', ['pizza_variant_id'], ['id'])
    op.create_foreign_key(op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
